# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\input_parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(624, 44)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_param_type = QtWidgets.QComboBox(Form)
        self.comboBox_param_type.setObjectName("comboBox_param_type")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.comboBox_param_type.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_param_type)
        self.lineEdit_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.horizontalLayout.addWidget(self.lineEdit_name)
        self.checkBox_parallel = QtWidgets.QCheckBox(Form)
        self.checkBox_parallel.setObjectName("checkBox_parallel")
        self.horizontalLayout.addWidget(self.checkBox_parallel)
        self.checkBox_other_size = QtWidgets.QCheckBox(Form)
        self.checkBox_other_size.setObjectName("checkBox_other_size")
        self.horizontalLayout.addWidget(self.checkBox_other_size)
        self.checkBox_init = QtWidgets.QCheckBox(Form)
        self.checkBox_init.setObjectName("checkBox_init")
        self.horizontalLayout.addWidget(self.checkBox_init)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_param_type.setItemText(0, _translate("Form", "int"))
        self.comboBox_param_type.setItemText(1, _translate("Form", "struct"))
        self.comboBox_param_type.setItemText(2, _translate("Form", "float"))
        self.comboBox_param_type.setItemText(3, _translate("Form", "double"))
        self.comboBox_param_type.setItemText(4, _translate("Form", "int*"))
        self.comboBox_param_type.setItemText(5, _translate("Form", "float*"))
        self.comboBox_param_type.setItemText(6, _translate("Form", "double*"))
        self.comboBox_param_type.setItemText(7, _translate("Form", "struct*"))
        self.checkBox_parallel.setText(_translate("Form", "Parallel"))
        self.checkBox_other_size.setText(_translate("Form", "Other Size"))
        self.checkBox_init.setText(_translate("Form", "init"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
