# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\struct_parameter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(583, 417)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_struct_type = QtWidgets.QComboBox(Form)
        self.comboBox_struct_type.setObjectName("comboBox_struct_type")
        self.comboBox_struct_type.addItem("")
        self.comboBox_struct_type.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_struct_type)
        self.lineEdit_struct_name = QtWidgets.QLineEdit(Form)
        self.lineEdit_struct_name.setObjectName("lineEdit_struct_name")
        self.horizontalLayout.addWidget(self.lineEdit_struct_name)
        self.label_parameter_count = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_parameter_count.setFont(font)
        self.label_parameter_count.setObjectName("label_parameter_count")
        self.horizontalLayout.addWidget(self.label_parameter_count)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(32, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget_struct_parameters = QtWidgets.QListWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_struct_parameters.sizePolicy().hasHeightForWidth())
        self.listWidget_struct_parameters.setSizePolicy(sizePolicy)
        self.listWidget_struct_parameters.setMinimumSize(QtCore.QSize(0, 225))
        self.listWidget_struct_parameters.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_struct_parameters.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.listWidget_struct_parameters.setObjectName("listWidget_struct_parameters")
        self.verticalLayout_2.addWidget(self.listWidget_struct_parameters)
        self.pushButton_add_struct_param = QtWidgets.QPushButton(Form)
        self.pushButton_add_struct_param.setObjectName("pushButton_add_struct_param")
        self.verticalLayout_2.addWidget(self.pushButton_add_struct_param)
        self.pushButton_remove_struct_item = QtWidgets.QPushButton(Form)
        self.pushButton_remove_struct_item.setObjectName("pushButton_remove_struct_item")
        self.verticalLayout_2.addWidget(self.pushButton_remove_struct_item)
        self.pushButton_to_json = QtWidgets.QPushButton(Form)
        self.pushButton_to_json.setObjectName("pushButton_to_json")
        self.verticalLayout_2.addWidget(self.pushButton_to_json)
        self.pushButton_from_json = QtWidgets.QPushButton(Form)
        self.pushButton_from_json.setObjectName("pushButton_from_json")
        self.verticalLayout_2.addWidget(self.pushButton_from_json)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.comboBox_struct_type.setItemText(0, _translate("Form", "struct"))
        self.comboBox_struct_type.setItemText(1, _translate("Form", "struct*"))
        self.label_parameter_count.setText(_translate("Form", "Parameter Count: 0"))
        self.pushButton_add_struct_param.setText(_translate("Form", "Add Item"))
        self.pushButton_remove_struct_item.setText(_translate("Form", "Remove Item"))
        self.pushButton_to_json.setText(_translate("Form", "To Json"))
        self.pushButton_from_json.setText(_translate("Form", "From Json"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
